version: "3"

services:
  app:
    container_name: aiq-subject-api
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app/
    env_file: .env.local
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: aiq-subject-db
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=aiq_subject_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
